---@alias TodoItemType
---|"undone"
---|"pending"
---|"done"
---|"cancelled"
---|"recurring"
---|"on_hold"
---|"important"
---|"ambiguous"
---|"ongoing"

---@class TodoItemDefinition
---@field literal string
---@field icon string
---@field hl string
